name: "Puente MQTT a MSSQL"
version: "2028.08.54"
slug: "mqtt2mssql-cfm"
description: "Escucha datos por MQTT y ejecuta INSERTS complejos en MSSQL usando pyodbc nativo"
url: "https://github.com/carferrer/mqtt2mssql-cfm"
image: "ghcr.io/carferrer/mqtt2mssql-cfm"
image_tag: "latest"
arch:
  - amd64
  - aarch64
init: false
options:
  log_level: "INFO"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "TuUsuariomqtt"
  mqtt_password: "TuContraseñamqtt"
  mqtt_id: "mqtt2mssql"
  mqtt_topic: "topic-mqtt2mssql"
  mssql_server: "192.168.1.X"
  mssql_port: 1433
  mssql_database: "TuBaseDatos"
  mssql_user: "TuUsuariomssql"
  mssql_password: "TuContraseñamssql"
schema:
  log_level: list(TRACE|DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL)
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password # Al poner 'password', Home Assistant oculta el texto en la interfaz por seguridad
  mqtt_id: str
  mqtt_topic: str
  mssql_server: str
  mssql_port: int
  mssql_database: str
  mssql_user: str
  mssql_password: password # Al poner 'password', Home Assistant oculta el texto en la interfaz por seguridad
